"""
=========================================================
LogiBridge - Model Training Pipeline (M1 Baseline)
Module 3 - Task C2 / Module 4 - Task D1
=========================================================
Trains baseline Keras neural network on the windowed feature dataset
(training_dataset.csv from generate_dataset.py):
- Checks Class 2 Recall gate (>= 95%)
- Checks overall validation accuracy gate (>= 88%)
- Saves model as models/cold_chain_model.tflite
- Saves the held-out validation split so optimisation/benchmark.py can
  report accuracy consistently across M1/M2/M3
=========================================================
"""

import argparse
import json
import os
import sys
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix

# Import the canonical feature-column list so training always matches what
# preprocessing.py / inference_service.py produce.
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_PIPELINE_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "data_pipeline"))
if DATA_PIPELINE_DIR not in sys.path:
    sys.path.insert(0, DATA_PIPELINE_DIR)

from preprocessing import FEATURE_COLUMNS

NORM_FEATURE_COLUMNS = [f"{c}_norm" for c in FEATURE_COLUMNS]


def locate_data_file(data_path):
    """Finds the training dataset even if executed from different working directories."""
    possible_paths = [
        data_path,
        os.path.join("..", data_path),
        os.path.join("training", "training_dataset.csv"),
        os.path.join("..", "training", "training_dataset.csv"),
        os.path.join("data_pipeline", "clean_data.csv"),
        os.path.join("..", "data_pipeline", "clean_data.csv"),
    ]
    for path in possible_paths:
        if os.path.exists(path):
            return path
    raise FileNotFoundError(
        f"Could not locate '{data_path}'. Please run generate_dataset.py first or specify --data path."
    )


def train_model(data_path, model_dir, class_weight_critical=3.0):
    resolved_data_path = locate_data_file(data_path)
    print(f"Loading windowed feature dataset from: {resolved_data_path}")
    df = pd.read_csv(resolved_data_path)

    missing = [c for c in NORM_FEATURE_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(
            f"Dataset at {resolved_data_path} is missing expected feature columns {missing}. "
            f"Re-run generate_dataset.py with the current preprocessing.py so the windowed "
            f"7-feature vectors are present."
        )

    if "split" not in df.columns:
        raise ValueError(
            f"{resolved_data_path} has no 'split' column. This file was generated by an older "
            f"version of generate_dataset.py that used a random shuffle-split -- which LEAKS "
            f"overlapping sliding windows between train and validation (adjacent windows share "
            f"up to 67% of their raw samples). Re-run generate_dataset.py with the current "
            f"version so train/val is split chronologically per class instead."
        )

    train_df = df[df["split"] == "train"]
    val_df = df[df["split"] == "val"]
    print(f"Chronological split (no shuffle -- avoids overlapping-window leakage): "
          f"{len(train_df)} train / {len(val_df)} val")

    X_train = train_df[NORM_FEATURE_COLUMNS].values
    y_train = train_df["label"].values
    X_test = val_df[NORM_FEATURE_COLUMNS].values
    y_test = val_df["label"].values

    # Build Keras Baseline Model (M1)
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(X_train.shape[1],)),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(3, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    print("Training baseline Keras model (M1)...")
    # Class weighting: penalize Critical-class (2) errors more heavily than
    # Normal/Warning. This directly targets the Warning<->Critical confusion
    # seen in the confusion matrix, without needing new data or a resimulation
    # -- standard practice for a class whose recall matters more than the
    # others (a missed Critical/spoilage event is the costliest error type).
    class_weight = {0: 1.0, 1: 1.0, 2: class_weight_critical}
    print(f"Using class_weight={class_weight} to prioritize Class-2 recall")
    model.fit(X_train, y_train, epochs=25, batch_size=16, verbose=1, class_weight=class_weight)

    # Evaluate model performance
    y_pred = np.argmax(model.predict(X_test), axis=1)
    print("\n--- Model Evaluation Report ---")
    print(classification_report(y_test, y_pred, zero_division=0))

    overall_accuracy = float(np.mean(y_pred == y_test)) * 100.0
    print(f"Overall Validation Accuracy: {overall_accuracy:.2f}%")
    if overall_accuracy < 88.0:
        print("[WARNING] Validation accuracy is below the 88% threshold required for "
              "pharmaceutical cold-chain monitoring (Task D1). Revisit feature "
              "extraction or model architecture before proceeding.")

    # Check Class 2 Recall Gate (>= 95%)
    cm = confusion_matrix(y_test, y_pred, labels=[0, 1, 2])
    class2_total = np.sum(cm[2, :])
    class2_recall = None
    if class2_total > 0:
        class2_recall = float(cm[2, 2] / class2_total)
        print(f"Class 2 (Spoilage Alert) Recall: {class2_recall * 100:.2f}%")
        if class2_recall < 0.95:
            print("[WARNING] Class 2 Recall is below 95% threshold! Model may require re-tuning.")
    else:
        print("[INFO] No Class 2 instances present in test set split.")

    report_dict = classification_report(y_test, y_pred, zero_division=0, output_dict=True)

    # Save Model & TFLite Float32 Baseline
    os.makedirs(model_dir, exist_ok=True)

    # 1. Save Keras Native Model
    keras_model_path = os.path.join(model_dir, "saved_model.keras")
    model.save(keras_model_path)
    print(f"Saved Keras model to: {keras_model_path}")

    # Also save raw weight ARRAYS (not a Keras file format at all). Both
    # tf.keras.models.load_model() and model.save_weights()/load_weights()
    # route through Keras's own HDF5/config serialization, which differs
    # between native Keras 3 and the legacy tf_keras backend that TFMOT
    # (imported by prune_quantise.py) forces -- so anything saved by one
    # backend's serializer can fail to load in the other's, even from the
    # same TensorFlow install, even with matching filenames. get_weights()/
    # set_weights() sidestep this entirely: they're plain lists of NumPy
    # arrays with no version-specific format to disagree about.
    weights_path = os.path.join(model_dir, "baseline_weights.npz")
    weight_arrays = model.get_weights()
    np.savez(weights_path, **{f"w{i}": w for i, w in enumerate(weight_arrays)})
    print(f"Saved baseline weights (Keras-version-safe, {len(weight_arrays)} arrays) to: {weights_path}")

    # 2. Convert and save TFLite Float32 baseline (M1)
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()

    tflite_path = os.path.join(model_dir, "cold_chain_model.tflite")
    with open(tflite_path, "wb") as f:
        f.write(tflite_model)

    print(f"Saved Float32 baseline TFLite model (M1) to: {tflite_path}")

    # 3. Save the held-out validation split so benchmark.py can report a
    #    consistent accuracy figure across M1/M2/M3.
    validation_path = os.path.join(model_dir, "validation_split.npz")
    np.savez(validation_path, X_test=X_test.astype(np.float32), y_test=y_test.astype(np.int64))
    print(f"Saved held-out validation split for benchmarking to: {validation_path}")

    # 4. Save a training_summary.json -- a reproducibility artifact recording
    # what this specific training run actually produced (accuracy, per-class
    # recall, gate pass/fail, dataset size), written both alongside the model
    # artifacts (model_dir) and under this script's own local models/ folder,
    # so the training/ subtree is never left empty even when --model-dir
    # points elsewhere (e.g. the project-root models/ used by benchmark.py).
    summary = {
        "timestamp": __import__("datetime").datetime.now().isoformat(),
        "feature_columns": NORM_FEATURE_COLUMNS,
        "n_train_samples": int(len(X_train)),
        "n_val_samples": int(len(X_test)),
        "epochs": 25,
        "overall_accuracy_pct": round(overall_accuracy, 4),
        "accuracy_gate_88pct_passed": bool(overall_accuracy >= 88.0),
        "class2_recall": round(class2_recall, 4) if class2_recall is not None else None,
        "class2_recall_gate_95pct_passed": bool(class2_recall is not None and class2_recall >= 0.95),
        "per_class_report": report_dict,
    }
    summary_paths = [os.path.join(model_dir, "training_summary.json")]
    local_models_dir = os.path.join(SCRIPT_DIR, "models")
    if os.path.abspath(local_models_dir) != os.path.abspath(model_dir):
        os.makedirs(local_models_dir, exist_ok=True)
        summary_paths.append(os.path.join(local_models_dir, "training_summary.json"))
    for sp in summary_paths:
        with open(sp, "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2)
        print(f"Saved training summary to: {sp}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="LogiBridge Model Training Pipeline")
    parser.add_argument("--data", type=str, default="training/training_dataset.csv", help="Path to training_dataset.csv")
    parser.add_argument("--model-dir", type=str, default="models", help="Directory to save output models")
    parser.add_argument("--seed", type=int, default=None,
                         help="Random seed (unset = different random init each run). Training takes "
                              "only ~15s on this dataset, so trying a few seeds is cheap if the first "
                              "attempt doesn't clear the accuracy/recall gates.")
    parser.add_argument("--class-weight-critical", type=float, default=3.0,
                         help="Loss weight for Class 2 (Critical) vs 1.0 for Normal/Warning. "
                              "Higher values push harder for Class-2 recall at some cost to "
                              "Normal/Warning precision -- there's currently slack to spend since "
                              "both sit at 100%% recall. Try 5.0-8.0 if 3.0 isn't enough.")
    args = parser.parse_args()

    if args.seed is not None:
        import numpy as _np
        tf.random.set_seed(args.seed)
        _np.random.seed(args.seed)
        print(f"Using fixed random seed: {args.seed}")

    train_model(args.data, args.model_dir, args.class_weight_critical)
